name: Multi-Deploy

variables:
- env: [dev,qa,stage,prod]
on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform fmt -check=true
      - name: Terraform validate
        run: terraform validate
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan (Dev)
        run: terraform plan -var-file=tfvars/dev.tfvars
      - name: Terraform Apply (Dev)
        run: terraform apply -var-file=envs/dev.tfvars -auto-approve
  deploy-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan (QA)
        run: terraform plan -var-file=tfvars/dev.tfvars
      - name: Terraform Apply (QA)
        run: terraform apply -var-file=envs/qa.tfvars -auto-approve
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan (STAGE)
        run: terraform plan -var-file=tfvars/dev.tfvars
      - name: Terraform Apply (STAGE)
        run: terraform apply -var-file=envs/stage.tfvars
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan (PROD)
        run: terraform plan -var-file=tfvars/dev.tfvars
      - name: Terraform Apply (PROD)
        run: terraform apply -var-file=envs/prod.tfvars